//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewDarkBot {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("der_darkiebot")]
        public string botname {
            get {
                return ((string)(this["botname"]));
            }
            set {
                this["botname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("f8ujic6q5tdvm7xz0vw15d64urasdg")]
        public string oauth {
            get {
                return ((string)(this["oauth"]));
            }
            set {
                this["oauth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("der_darkie")]
        public string channel {
            get {
                return ((string)(this["channel"]));
            }
            set {
                this["channel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gp762nuuoqcoxypju8c569th9wz7q5")]
        public string clientid {
            get {
                return ((string)(this["clientid"]));
            }
            set {
                this["clientid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("txqkpyfvcc7omckl47gugyubsw31ak")]
        public string apiclientid {
            get {
                return ((string)(this["apiclientid"]));
            }
            set {
                this["apiclientid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("zyksswdg5uqfd2vpq3z6i7b9sxmunx")]
        public string apisecret {
            get {
                return ((string)(this["apisecret"]));
            }
            set {
                this["apisecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c83ab1b89bfe4c96b5eb5b6e997a47cc")]
        public string wowapiclientid {
            get {
                return ((string)(this["wowapiclientid"]));
            }
            set {
                this["wowapiclientid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yq2jhvhfDQy9z0TgLjJS3A2VZGVVpNGY")]
        public string wowapisecret {
            get {
                return ((string)(this["wowapisecret"]));
            }
            set {
                this["wowapisecret"] = value;
            }
        }
    }
}
